services:
  - type: web
    name: mexc-spread-bot
    env: python
    plan: free
    build: { pythonVersion: "3.12.3" }
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
